### ISSUE TITLE
Add support for content encoding negotiation

### ISSUE THREAD

**Issue by JuanCarlosGonzalez** [aws/aws-appsync-community#15]
It would be great that AppSync services support content encoding negotiation as API Gateway does. In order to accomplish it, AppSync services should honor Accept-Encoding header a provide compressed responses according to accepted compressions.

We've moved some of our backend services from Api Gateway + AWS Lambda pattern to AWS AppSync and we miss this feature.

Best regards,

Juan Carlos González

**Comment by vlekakis** [comment]
Hi 

Thank you for your interest in AppSync! I will bring your feature request in the team. 
I'm leaving this issue here open, to see if the rest if the community is interested in this as well.

**Comment by fgiarritiello** [comment]
Very interested in this feature. Thanks

**Comment by RogerVin** [comment]
also very interested in this feature

**Comment by jazztong** [comment]
We recently use AppSync heavily in our service, it will be great if this feature is enabled.

**Comment by joemastersemison** [comment]
+1, we would love to use gzip

**Comment by yvele** [comment]
@joemastersemison you can already use gzip with AWS AppSync if you setup CloudFront yourself.

![Screenshot 2019-10-16 at 09 48 27](https://user-images.githubusercontent.com/4225430/66899020-8db7b480-effa-11e9-84cc-8d1107a88c65.png)



Here is a CloudFormation stack example of how I did it:

```yaml
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled : true
        IPV6Enabled : true
        HttpVersion : http
        ...

        # Specific to GraphQL API
        CacheBehaviors:
          - PathPattern     : /graphql*
            TargetOriginId  : ApiAppSyncGraphQL
            MinTTL          : 0
            MaxTTL          : 0
            DefaultTTL      : 0
            Compress        : true # Automatic gzip
            AllowedMethods  : [HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH]
            ViewerProtocolPolicy: https-only
            ForwardedValues: # Specifies how CloudFront handles query strings or cookies
              QueryString: true
              Headers:
                # Custom "Authorization" and "Host" should NOT be forwarded!
                - Origin
                - Referer

```

**Comment by marcelalburg** [comment]
Any news about AppSync support compression?

**Comment by markoff-s** [comment]
+1

**Comment by alexchumak** [comment]
👍

**Comment by oakstreetrec** [comment]
+1

**Comment by orcaman** [comment]
+1

**Comment by mperone** [comment]
@Vlaaaaaaad - why the thumbs down on the last few responses from people? Do you know a better way to do this or is this request misguided in some other way? From my perspective, compression on the AppSync graphql responses would be a big deal.

@yvele - would you mind posting some more details on your cloudformation example? There hasn't been any movement on this in years so I think it may be that your cloudformation example is the best (only?) way to do it. I tried parsing your eaxmple but I'm not sure I 100% understand. And when I tried the serverless-appsync-cloudfront plugin that indicates it would set it up for you, it didn't seem to work.

**Comment by Vlaaaaaaad** [comment]
> @Vlaaaaaaad - why the thumbs down on the last few responses from people? Do you know a better way to do this or is this request misguided in some other way? From my perspective, compression on the AppSync graphql responses would be a big deal.

Because +1 comments don't help at all: they don't push the discussion further and they don't count as votes (reactions on the top comment count, not comments on the issues). The only thing those comments add is spam, hence the thumbs down.

**Comment by PeteDuncanson** [comment]
Not sure if thumbs up or down really do much on here to be honest. 

![image](https://user-images.githubusercontent.com/1674590/129390124-5ac353b3-f928-492f-a412-2f4e4e035138.png)

Been going around in circles on this one and still can't get anything working. There are a few cut and paste samples but none I can get working sadly.

**Comment by mperone** [comment]
I dug into it tonight and got it working. Here's the CloudFormation setup I'm using. I ordered the properties in the same order you'd find them on the console GUI if were setting it up that way:

Thank you to @yvele, this is essentially his set up with a few added details.

One note: the ForwardedValues property is deprecated and it seems that eventually we'll have to change to a CachePolicy and OriginRequestPolicy. I tried a few different setups but unfortunately I couldn't get it to work using those.

Note - after you get the CloudFront Distribution up and running, don't forget to change your app to switch to the new endpoint! i.e. fetching from https://something.appsync-api.region.amazonaws.com/graphql -> https://something.cloudfront.net/graphql

```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ### Your description here ###
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: AppSyncGraphQLApi
            DomainName: ### Your GraphQL endpoint here (no "https://" prefix and no "/graphql" postfix) ###
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
              OriginSSLProtocols:
                - TLSv1
        DefaultCacheBehavior:
          TargetOriginId: AppSyncGraphQLApi
          Compress: true
          ViewerProtocolPolicy: https-only
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
          ForwardedValues:
            Headers:
              - Origin
              - Referer
            QueryString: true
          MinTTL: 0
          MaxTTL: 0
          DefaultTTL: 0
        PriceClass: PriceClass_100
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
Outputs:
  CloudFrontDistributionDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: CloudFront-CloudFrontDistributionDomain
```
