### ISSUE TITLE
[Question] Fine-grained access control for specific attributes

### ISSUE THREAD

**Issue by explaura** [aws/aws-appsync-community#27]
I'm implementing role based access control using `IAM_AUTHORIZATION` and am wondering if it’s possible to control access to specific attributes in AppSync?

I’m currently whitelisting specific GraphQL queries, mutations and subscriptions based on role which is working fine, but not sure if it's possible to get finer-grained than that.

I'd like something like the following, where `myAttribute` access is denied:
```
PortalAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "PortalAdminPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "appsync:GraphQL"
            Resource:
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Mutation/fields/updateEnvironment"
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Mutation/fields/createEnvironment"
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Mutation/fields/deleteEnvironment"
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Query/fields/getEnvironment"
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Subscription/fields/updatedEnvironment"
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Subscription/fields/deletedEnvironment"
          - Effect: Deny
            Action:
              - "appsync:GraphQL"
            Resource:
              - !Sub "arn:aws:appsync:${AWS::Region}:${AWS::AccountId}:apis/${GraphqlApiId}/types/Environment/fields/myAttribute"
      Roles:
        - Ref: "PortalAdminRole"
```
